#!/usr/bin/env bash

set -e

SELECTED_VM_FILE="$HOME/.docker-forward-vm"
DEFAULT_VM_NAME="boot2docker-vm"

get_selected_vm() {
  if [[ -f $SELECTED_VM_FILE ]]; then
    vm_name="$(cat "$SELECTED_VM_FILE")"
    if [[ "$vm_name" == "" ]]; then
      echo "$DEFAULT_VM_NAME"
    else
      echo "$vm_name"
    fi
  else
    echo "$DEFAULT_VM_NAME"
  fi
}
