#!/usr/bin/env bash

set -e

SELECTED_VM_FILE="$HOME/.docker-forward-vm"
DEFAULT_VM_NAME="boot2docker-vm"

RULES_REGEX="^NIC 1 Rule.*"
PROTOCOL_REGEX="(tcp|udp)"
PORT_REGEX="guest port = ([[:digit:]]*)"

get_selected_vm() {
  vm_name="$DEFAULT_VM_NAME"
  if [[ -f $SELECTED_VM_FILE ]]; then
    vm_name="$(cat "$SELECTED_VM_FILE")"
    if [[ -n "$vm_name" ]]; then
      vm_name="$vm_name"
    fi
  fi
  echo "$vm_name"
}

extract() {
  [[ "$1" =~ $2 ]]
  echo "${BASH_REMATCH[1]}"
}

list_vms() {
  for line in "$(VBoxManage list vms)"; do
    while IFS=$' ' read -r vm id; do
      echo "$vm" | tr -d '\"'
    done <<< "$line"
  done
}

list_forwarded_ports() {
  vm_info="$(VBoxManage showvminfo $(get_selected_vm))"
  while IFS=$'\n' read -r line ; do
    if [[ "$line" =~ $RULES_REGEX ]]; then
      protocol=$(extract "$line" "$PROTOCOL_REGEX")
      port=$(extract "$line" "$PORT_REGEX")
      echo "$protocol/$port"
    fi
  done <<< "$vm_info"
}

vm_list_completions() {
    echo -e "$(list_vms)"
    exit 0
}
