#!/usr/bin/env bash
set -e

. $_DOCKER_FORWARD_ROOT/libexec/utils
. $_DOCKER_FORWARD_ROOT/libexec/virtualbox

# Provide docker-forward completions
if [[ "$1" == "--complete" ]]; then
  vm_list_completions
fi

update_vm_name() {
  name="$1"
  echo "$name" > $SELECTED_VM_FILE
}

case "$1" in
  "")
      get_selected_vm;;
  *)
      update_vm_name "$1";;
esac
