#!/usr/bin/env bash
set -e

. $_DOCKER_FORWARD_ROOT/libexec/utils
. $_DOCKER_FORWARD_ROOT/libexec/virtualbox

echo "TCP ports: $(sort_shorter_first "$(list_forwarded_ports "tcp")" | tr "\n" " ")"
echo "UDP ports: $(sort_shorter_first "$(list_forwarded_ports "udp")" | tr "\n" " ")"
