#!/usr/bin/env bash

set -e

. $_DOCKER_FORWARD_ROOT/libexec/virtualbox

# Provide docker-forward completions
if [[ "$1" == "--complete" ]]; then
  sort_shorter_first "$(list_forwarded_ports "udp")"
  exit 0
fi

remove_port "udp" $1
