#!/usr/bin/env bash
set -e

. $_DOCKER_FORWARD_ROOT/libexec/commons

# Provide docker-forward completions
if [[ "$1" == "--complete" ]]; then
  echo -e "$(list_vms)"
  exit 0
fi

list_forwarded_ports "$1" | gawk -f "$AWK_SCRIPTS/print-open-ports"
