#!/usr/bin/env bash
set -e

. $_DOCKER_FORWARD_ROOT/libexec/commons

list_vms() {
  echo "$(VBoxManage list vms | awk 'BEGIN {FS=" ";}{gsub("\"","",$1);print $1;}')"
}

# Provide docker-forward completions
if [[ "$1" == "--complete" ]]; then
  echo -e "$(list_vms)"
fi

update_vm_name() {
  name="$1"
  echo "$name" > $SELECTED_VM_FILE
}

case "$1" in
  "")
      get_selected_vm;;
  *)
      if [[ "$1" != "--complete" ]]; then
        update_vm_name "$1"
      fi;;
esac
