#!/usr/bin/env bash

set -e

SELECTED_VM_FILE="$HOME/.docker-forward-vm"
DEFAULT_VM_NAME="boot2docker-vm"

get_selected_vm() {
  vm_name="$DEFAULT_VM_NAME"
  if [[ -f $SELECTED_VM_FILE ]]; then
    vm_name="$(cat "$SELECTED_VM_FILE")"
    if [[ -n "$vm_name" ]]; then
      vm_name="$vm_name"
    fi
  fi
  echo "$vm_name"
}

extract() {
  [[ "$1" =~ $2 ]]
  echo "${BASH_REMATCH[1]}"
}

sort_shorter_first() {
  echo "$(echo "$1" | awk '{ print length, $0 }' | sort -n | cut -d" " -f 2 -)"
}
