#!/usr/bin/env bash

set -e

. $_DOCKER_FORWARD_ROOT/libexec/utils

RULES_REGEX="^NIC 1 Rule.*"
PROTOCOL_REGEX="(tcp|udp)"
PORT_REGEX="guest port = ([[:digit:]]*)"

port_name() {
  echo "$1-$2"
}

is_tcp() {
  [[ "$1" == "TCP" ]]
}

is_udp() {
 [[ "$2" == "UDP" ]]
}

add_port() {
  VBoxManage controlvm "$(get_selected_vm)" natpf1 "$(port_name $1 $2),$1,,$2,,$2"
}

remove_port() {
  VBoxManage controlvm "$(get_selected_vm)" natpf1 delete "$(port_name $1 $2)"
}

list_vms() {
  for line in "$(VBoxManage list vms)"; do
    while IFS=$' ' read -r vm id; do
      echo "$vm" | tr -d '\"'
    done <<< "$line"
  done
}

list_forwarded_ports() {
  vm_info="$(VBoxManage showvminfo $(get_selected_vm))"
  while IFS=$'\n' read -r line ; do
    if [[ "$line" =~ $RULES_REGEX ]]; then
      protocol=$(extract "$line" "$PROTOCOL_REGEX")
      port=$(extract "$line" "$PORT_REGEX")
      echo "${protocol^^}/$port"
    fi
  done <<< "$vm_info"
}

is_port_forwarded() {
  is_forwarded=0
  while IFS=$'\n' read -r line ; do
    while IFS="/" read -r protocol port ; do
      if [[ "$protocol" == "$1" ]] && [[ "$port" == "$2" ]]; then
        is_forwarded=1
        break 2
      fi
    done <<< "$line"
  done <<< "$(list_forwarded_ports)"
  echo "$is_forwarded"
}

vm_list_completions() {
    echo -e "$(list_vms)"
    exit 0
}
